### ISSUE TITLE
Changes to `poisson-boltzman` example needed to export `.vtk`

### ISSUE THREAD

**Issue by colinthart** [JuliaSmoothOptimizers/PDENLPModels.jl#60]
I was following along with the [poisson-boltzman example](https://github.com/JuliaSmoothOptimizers/PDENLPModels.jl/tree/main/docs/src/poisson-boltzman.md) from  your JuliaCon 2022 talk [PDE-constrained optimization using JuliaSmoothOptimizers](https://www.youtube.com/watch?v=BvReBcMyujQ) and I found that I had to make some small changes to get it to export `.vtk` results correctly.  Namely, the references to `nlp._` in the following lines

```julia
yfv = stats.solution[1:Gridap.FESpaces.num_free_dofs(nlp.pdemeta.Ypde)]
yh  = FEFunction(nlp.pdemeta.Ypde, yfv)
ufv = stats.solution[1+Gridap.FESpaces.num_free_dofs(nlp.pdemeta.Ypde):end]
uh  = FEFunction(nlp.Ycon, ufv)
writevtk(nlp.tnrj.trian,"results",cellfields=["uh"=>uh, "yh"=>yh])
```

had to be changed to `nlp.pdemeta._`

```julia
yfv = stats.solution[1:Gridap.FESpaces.num_free_dofs(nlp.pdemeta.Ypde)]
yh  = FEFunction(nlp.pdemeta.Ypde, yfv)
ufv = stats.solution[1+Gridap.FESpaces.num_free_dofs(nlp.pdemeta.Ypde):end]
uh  = FEFunction(nlp.pdemeta.Ycon, ufv)
writevtk(nlp.pdemeta.tnrj.trian,"results",cellfields=["uh"=>uh, "yh"=>yh])
```

Thank you for your talk.  I look forward to learning more about your project.

**Comment by tmigot** [comment]
Thanks @colinthart for catching this one! I open a PR to fix it.
